from app.models.admin import (
    AdminAlertOutboxDispatchPlan,
    AdminAlertOutboxEntry,
    AuditArchiveAnchor,
    AuditChainHead,
    AuditLog,
    BackgroundTask,
    BackgroundTaskAttempt,
    BugExternalSyncOperation,
    BugRecord,
    SecurityControlLock,
)
from app.models.base import Base
from app.models.code_judge import (
    CodeJudgeAttempt,
    CodeProblem,
    CodeProblemVersion,
    CodeSubmission,
)
from app.models.content import (
    ContentDraft,
    ContentPageRecord,
    ContentPageVersion,
    ContentScriptAsset,
    ContentScriptAssetScanRun,
    ContentScriptHostPolicy,
)
from app.models.content_platform import (
    CourseClassReleaseBinding,
    CourseRelease,
    CourseReleaseUnit,
)
from app.models.course import (
    Assignment,
    AssignmentClassPolicy,
    ClassKnowledgeSnapshot,
    Course,
    CourseClass,
    CourseCollaborator,
    CourseUnit,
    CourseUnitClassPlan,
    KnowledgeSnapshotRun,
    LearningEvent,
    PointLedger,
    Submission,
    UserKnowledgeSnapshot,
)
from app.models.course_relationship import (
    CourseAdmissionClass,
    CourseEnrollment,
    CourseInformationRevision,
    CourseJoinRequest,
)
from app.models.learning_evidence import (
    LearningActivityProjection,
    LearningActivityRuntime,
    LearningCompletionRule,
    LearningEvidenceEvent,
    LearningResumeProjection,
    LearningRuleActivation,
    LearningRuleClassBinding,
    LegacyAccessEntitlement,
)
from app.models.school import (
    ClassGroup,
    ClassJoinRequest,
    ClassMembership,
    School,
    SchoolMembership,
)
from app.models.teacher_application import TeacherApplication
from app.models.user import AuthSession, LoginAttempt, PasswordResetToken, User

__all__ = [
    "AdminAlertOutboxDispatchPlan",
    "AdminAlertOutboxEntry",
    "Assignment",
    "AssignmentClassPolicy",
    "AuditArchiveAnchor",
    "AuditChainHead",
    "AuditLog",
    "AuthSession",
    "BackgroundTask",
    "BackgroundTaskAttempt",
    "Base",
    "BugExternalSyncOperation",
    "BugRecord",
    "ClassGroup",
    "ClassJoinRequest",
    "ClassKnowledgeSnapshot",
    "ClassMembership",
    "CodeJudgeAttempt",
    "CodeProblem",
    "CodeProblemVersion",
    "CodeSubmission",
    "ContentDraft",
    "ContentPageRecord",
    "ContentPageVersion",
    "ContentScriptAsset",
    "ContentScriptAssetScanRun",
    "ContentScriptHostPolicy",
    "Course",
    "CourseAdmissionClass",
    "CourseClass",
    "CourseClassReleaseBinding",
    "CourseCollaborator",
    "CourseEnrollment",
    "CourseInformationRevision",
    "CourseJoinRequest",
    "CourseRelease",
    "CourseReleaseUnit",
    "CourseUnit",
    "CourseUnitClassPlan",
    "KnowledgeSnapshotRun",
    "LearningActivityProjection",
    "LearningActivityRuntime",
    "LearningCompletionRule",
    "LearningEvent",
    "LearningEvidenceEvent",
    "LearningResumeProjection",
    "LearningRuleActivation",
    "LearningRuleClassBinding",
    "LegacyAccessEntitlement",
    "LoginAttempt",
    "PasswordResetToken",
    "PointLedger",
    "School",
    "SchoolMembership",
    "SecurityControlLock",
    "Submission",
    "TeacherApplication",
    "User",
    "UserKnowledgeSnapshot",
]
