"""Export the v2 portal DTO dependency closure from the authoritative OpenAPI schema.

Run from the repository root with Python; this does not connect to a database.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import sys

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))


def _type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    for union in ("anyOf", "oneOf"):
        if union in schema:
            return " | ".join(_type(value) for value in schema[union])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{_type(schema.get('items', {}))}>"
    if kind == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        if not properties:
            extra = schema.get("additionalProperties", True)
            return "Record<string, never>" if extra is False else f"Record<string, {_type(extra) if isinstance(extra, dict) else 'unknown'}>"
        required = set(schema.get("required", []))
        return "{\n" + "\n".join(f"  {name}{'' if name in required else '?'}: {_type(value)};" for name, value in properties.items()) + "\n}"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def generate() -> str:
    os.environ["ASTRA_AUTO_CREATE_TABLES"] = "false"
    from app.core.config import get_settings
    get_settings.cache_clear()
    from app.main import create_app
    specification = create_app().openapi()
    schemas = specification["components"]["schemas"]
    v2_paths = {path: value for path, value in specification["paths"].items() if path.startswith(get_settings().api_prefix + "/v2/")}
    roots = re.findall(r'"\$ref":\s*"#/components/schemas/([^"]+)"', json.dumps(v2_paths))
    pending, found = list(roots), set()
    while pending:
        name = pending.pop()
        if name in found:
            continue
        found.add(name)
        pending.extend(re.findall(r'"\$ref":\s*"#/components/schemas/([^"]+)"', json.dumps(schemas[name])))
    output = "// Generated by backend/scripts/export_portal_contracts.py. Do not edit DTOs by hand.\n\n"
    return output + "\n\n".join(f"export type {name} = {_type(schemas[name])};" for name in sorted(found)) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = BACKEND.parent / "qianduan" / "src" / "portal" / "api-v2.generated.ts"
    output = generate()
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != output:
            raise SystemExit("Portal v2 DTOs differ from backend OpenAPI; regenerate them")
        print("Portal v2 DTOs match backend OpenAPI")
    else:
        target.parent.resolve(strict=True)
        target.write_text(output, encoding="utf-8")
        print(f"Generated {target.relative_to(BACKEND.parent)}")


if __name__ == "__main__":
    main()
