// Generated by backend/scripts/export_portal_contracts.py. Do not edit DTOs by hand.

export type CandidateActionRead = {
  candidate_id: number;
  status: "submitted" | "approved" | "rejected" | "withdrawn";
  review_version: number;
};

export type CandidateDetailRead = {
  candidate_id: number;
  batch_id: number;
  course_id: number;
  course_title: string;
  school_id: number;
  revision_id: number;
  base_release_id: number | null;
  review_item_id: number;
  review_version: number;
  status: "submitted" | "approved" | "rejected" | "withdrawn";
  review_note: string | null;
  reviewed_by_user_id: number | null;
  reviewed_at: string | null;
  created_at: string;
  published_release_id: number | null;
  candidate_sha256: string;
  snapshot: CourseSnapshotRead;
  baseline: CourseSnapshotRead;
  impact: CourseImpactRead;
  result_policies: Record<string, "keep" | "redo">;
  dependencies: Record<string, unknown>;
  source_revision_id: number | null;
  submitted_by_user_id: number;
  note: string | null;
  stale: boolean;
  entity_labels?: Record<string, Record<string, string>>;
};

export type CandidatePageRead = {
  items: Array<CandidateSummaryRead>;
  total: number;
  offset: number;
  limit: number;
  next_offset: number | null;
};

export type CandidateSummaryRead = {
  candidate_id: number;
  batch_id: number;
  course_id: number;
  course_title: string;
  school_id: number;
  revision_id: number;
  base_release_id: number | null;
  review_item_id: number;
  review_version: number;
  status: "submitted" | "approved" | "rejected" | "withdrawn";
  review_note: string | null;
  reviewed_by_user_id: number | null;
  reviewed_at: string | null;
  created_at: string;
  published_release_id: number | null;
  candidate_sha256: string;
};

export type ChartSeries = {
  name: string;
  values: Array<number>;
};

export type CheckpointBlock = {
  blockId: string;
  type: "checkpoint";
  checkpointKey: string;
  title: string;
  prompt: string;
  mode?: "inline" | "question-set";
  questionSetKey?: string | null;
  responseType?: "single-choice" | "multiple-choice" | "numeric" | "short-text" | null;
  choices?: Array<CheckpointChoice>;
  correctChoiceIds?: Array<string>;
  numericAnswer?: number | null;
  tolerance?: number | null;
  acceptedAnswers?: Array<string>;
  maxAttempts?: number | null;
};

export type CheckpointChoice = {
  choiceId: string;
  label: string;
};

export type ContentPageV2 = {
  schemaVersion?: "astra-content-page-v2";
  slug: string;
  galaxy: string;
  subject: string;
  title: string;
  summary: string;
  layout?: string;
  status?: "draft" | "published" | "archived";
  version: string;
  blocks: Array<HeroBlock | LearningTaskBlock | RichTextBlock | MediaBlock | OfficialSimulationBlock | ResourceBlock | CheckpointBlock | SourcesBlock>;
  courseUnit?: CourseUnitRefV2 | null;
};

export type CourseAdmissionClassRead = {
  class_id: number;
  name: string;
  status: string;
};

export type CourseClassReleaseBindingRead = {
  id: number;
  course_class_id: number;
  course_release_id: number;
  binding_revision: number;
  previous_binding_id?: number | null;
  bound_by_user_id: number;
  binding_reason?: string | null;
  bound_at: string;
};

export type CourseCreateCommand = {
  client_request_id: string;
  school_id: number;
  title: string;
  summary?: string | null;
  academic_year: string;
  schedule_text: string;
  total_hours: number;
  galaxy_key: string;
  subject_key: string;
  admission_mode: "open" | "class_restricted";
  collaborator_user_ids?: Array<number>;
  admission_class_ids?: Array<number>;
  level_key?: string | null;
};

export type CourseDraftCommand = {
  client_request_id: string;
  expected_revision: number;
  expected_state_token: string;
  settings: CourseSettings;
  units: Array<CourseUnitWrite>;
};

export type CourseDraftReadV2 = {
  course_id: number;
  family_id: number | null;
  revision: number;
  revision_id: number | null;
  state_token: string;
  settings: CourseSettings;
  units: Array<CourseDraftUnitReadV2>;
  resources: Array<ResourceVersionRead>;
  warnings?: Array<string>;
};

export type CourseDraftUnitReadV2 = {
  id: number;
  content_draft_id?: number | null;
  revision: number;
  activity_key: string;
  title: string;
  position: number;
  content_slug?: string | null;
  content_schema_sha256?: string | null;
  last_editor_user_id?: number | null;
  content?: ContentPageV2 | null;
  origin_key: string;
  block_origins: Record<string, string>;
  resource_version_id: number | null;
};

export type CourseForkCommand = {
  client_request_id: string;
  settings: CourseSettings;
  source_release_id?: number | null;
  source_revision_id?: number | null;
  expected_source_revision?: number | null;
};

export type CourseForkRead = {
  course: CourseWorkflowRead;
  draft: CourseDraftReadV2;
  copied_units: number;
  warnings: Array<string>;
};

export type CourseImpactRead = {
  settings: Array<SettingChangeRead>;
  units: Array<UnitImpactRead>;
  removed_units: Array<RemovedUnitRead>;
  sync?: SyncImpactRead | null;
};

export type CourseInformationRevisionRead = {
  id: number;
  course_id: number;
  revision_number: number;
  edit_revision: number;
  information_snapshot: Record<string, unknown>;
  teacher_ids_snapshot: Array<number>;
  status: string;
  created_by_user_id: number;
  submitted_at?: string | null;
  reviewed_by_user_id?: number | null;
  reviewed_at?: string | null;
  review_note?: string | null;
  created_at: string;
  updated_at: string;
};

export type CourseMediaPage = {
  items: Array<CourseMediaRead>;
  total: number;
  offset: number;
  limit: number;
  next_offset: number | null;
};

export type CourseMediaRead = {
  asset_key: string;
  source_course_id: number;
  filename: string;
  media_type: "image" | "audio" | "video" | "document";
  content_type: string;
  size_bytes: number;
  content_sha256: string;
  created_at: string;
};

export type CourseReleaseRead = {
  id: number;
  course_id: number;
  release_number: number;
  draft_revision: number;
  schema_version: string;
  title: string;
  summary?: string | null;
  completion_rule_id?: number | null;
  completion_rule_sha256: string;
  package_sha256: string;
  published_by_user_id: number;
  published_at: string;
  units: Array<CourseReleaseUnitRead>;
};

export type CourseReleaseUnitRead = {
  id: number;
  source_course_unit_id: number;
  activity_key: string;
  title: string;
  position: number;
  content_slug: string;
  content_page_version_id: number;
  content_schema_sha256: string;
  media_snapshot?: Array<Record<string, unknown>>;
  content: Record<string, unknown>;
  access_state?: "open" | "locked";
  lock_reasons?: Array<string>;
};

export type CourseRevisionPageRead = {
  items: Array<CourseRevisionSummaryRead>;
  total: number;
  offset: number;
  limit: number;
  next_offset: number | null;
};

export type CourseRevisionRead = {
  id: number;
  course_id: number;
  revision_number: number;
  content_sha256: string;
  created_by_user_id: number;
  created_at: string;
  snapshot: Record<string, unknown>;
};

export type CourseRevisionSummaryRead = {
  id: number;
  course_id: number;
  revision_number: number;
  content_sha256: string;
  created_by_user_id: number;
  created_at: string;
};

export type CourseSettings = {
  school_id: number;
  title: string;
  summary?: string | null;
  academic_year: string;
  schedule_text: string;
  total_hours: number;
  galaxy_key: string;
  subject_key: string;
  admission_mode: "open" | "class_restricted";
  collaborator_user_ids?: Array<number>;
  admission_class_ids?: Array<number>;
  level_key?: string | null;
};

export type CourseSnapshotRead = {
  settings: Record<string, unknown>;
  units: Array<SnapshotUnitRead>;
};

export type CourseTeacherRead = {
  user_id: number;
  username: string;
  display_name: string;
  role: string;
  is_creator: boolean;
};

export type CourseUnitCompletionV1 = {
  preset: "experiment_operation" | "checkpoint_passed" | "assignment_reviewed";
  checkpointKey?: string | null;
  assignmentId?: number | null;
};

export type CourseUnitRefV2 = {
  courseId: string;
  unitId: string;
  order: number;
  title: string;
  completion?: CourseUnitCompletionV1 | null;
};

export type CourseUnitWrite = {
  id?: number | null;
  activity_key?: string | null;
  resource_version_id?: number | null;
  title: string;
  position: number;
  content: ContentPageV2;
};

export type CourseWorkflowRead = {
  id: number;
  school_id: number;
  creator_user_id: number;
  course_code?: string | null;
  title: string;
  summary?: string | null;
  academic_year: string;
  schedule_text: string;
  total_hours: number;
  galaxy_key: string;
  subject_key: string;
  admission_mode: "open" | "class_restricted";
  current_information_revision_id?: number | null;
  status: string;
  teachers: Array<CourseTeacherRead>;
  admission_classes: Array<CourseAdmissionClassRead>;
  information_revision: CourseInformationRevisionRead;
  has_published_content: boolean;
  content_status: "not_published" | "published";
  content_status_label: string;
  active_student_count?: number;
  created_at: string;
  updated_at: string;
  family_id: number | null;
  source_course_id: number | null;
  source_release_id: number | null;
  source_revision_id: number | null;
  workflow_generation: number;
  level_key: string | null;
  draft_settings: CourseSettings;
};

export type DataChartConfig = {
  kind?: "bar" | "line";
  title: string;
  labels: Array<string>;
  series: Array<ChartSeries>;
  y_label?: string;
};

export type FunctionGraphConfig = {
  formula: string;
  parameters?: Array<FunctionParameter>;
  x_min?: number;
  x_max?: number;
  y_min?: number;
  y_max?: number;
  samples?: number;
};

export type FunctionParameter = {
  key: string;
  label: string;
  value: number;
  minimum: number;
  maximum: number;
  step: number;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type HeroBlock = {
  blockId: string;
  type: "hero";
  title: string;
  summary: string;
  eyebrow?: string | null;
  badges?: Array<string>;
};

export type LearningLevelRead = {
  key: string;
  title: string;
};

export type LearningSpaceRead = {
  key: string;
  view: string;
  title: string;
  entry: string;
  kind: "legacy" | "bundle";
  accent: string;
};

export type LearningSpacesRead = {
  schema_version: "astra-learning-spaces-v1";
  spaces: Array<LearningSpaceRead>;
  levels: Array<LearningLevelRead>;
};

export type LearningTaskBlock = {
  blockId: string;
  type: "learning-task";
  title: string;
  prompt: string;
  outcomes?: Array<string>;
  steps?: Array<string>;
  concepts?: Array<string>;
};

export type LegacyResourceConfig = Record<string, never>;

export type MediaBlock = {
  blockId: string;
  type: "media";
  title?: string | null;
  mediaType: "image" | "diagram" | "audio" | "video" | "document";
  assetKey: string;
  alt?: string | null;
  caption?: string | null;
  transcript?: string | null;
};

export type OfficialSimulationBlock = {
  blockId: string;
  type: "official-simulation";
  title: string;
  simulationKey: string;
  instructions: string;
  fallbackMarkdown?: string | null;
};

export type PublicationReceiptRead = {
  items: Array<PublishedCandidateRead>;
};

export type PublishCommand = {
  client_request_id: string;
  items: Array<PublishSelection>;
  note?: string | null;
};

export type PublishSelection = {
  candidate_id: number;
  expected_review_version: number;
};

export type PublishedCandidateRead = {
  release: CourseReleaseRead;
  binding: CourseClassReleaseBindingRead;
  next_draft_revision: number;
  candidate_id: number;
  course_id: number;
};

export type RemovedUnitRead = {
  unit_id: number;
  title: string;
};

export type ResourceBlock = {
  blockId: string;
  type: "resource";
  title: string;
  resourceVersionId: number;
  configuration?: FunctionGraphConfig | DataChartConfig | LegacyResourceConfig;
  instructions: string;
};

export type ResourceInstallationRead = {
  installed_versions: number;
  catalogue_size: number;
};

export type ResourcePage = {
  items: Array<ResourceVersionRead>;
  total: number;
  limit: number;
  offset: number;
  next_offset: number | null;
};

export type ResourcePreview = {
  configuration?: FunctionGraphConfig | DataChartConfig | LegacyResourceConfig;
};

export type ResourcePreviewRead = {
  resource_version_id: number;
  renderer: string;
  configuration: Record<string, unknown>;
  view: Record<string, unknown>;
};

export type ResourceVersionRead = {
  id: number;
  resource_key: string;
  space_key: string;
  subject_key: string;
  kind: "activity" | "template" | "media";
  version_number: number;
  title: string;
  renderer: string;
  definition: Record<string, unknown>;
  capabilities: Record<string, unknown>;
  provenance: Record<string, unknown>;
  content_sha256: string;
};

export type RestoreDraftCommand = {
  client_request_id: string;
  expected_revision: number;
  expected_state_token: string;
  release_id: number;
};

export type ReviewActionRead = {
  candidate_id: number;
  status: "submitted" | "approved" | "rejected" | "withdrawn";
  review_version: number;
  course_id: number;
  review_item_id: number;
};

export type ReviewCommand = {
  client_request_id: string;
  items: Array<ReviewSelection>;
  decision: "approved" | "rejected";
  note?: string | null;
};

export type ReviewReceiptRead = {
  items: Array<ReviewActionRead>;
};

export type ReviewSelection = {
  review_item_id: number;
  expected_version: number;
};

export type RichTextBlock = {
  blockId: string;
  type: "rich-text";
  title?: string | null;
  markdown: string;
};

export type SettingChangeRead = {
  field: string;
  before_recorded: boolean;
  before: unknown;
  after: unknown;
};

export type SkippedCourseRead = {
  course_id: number;
  reason: string;
};

export type SnapshotUnitRead = {
  id: number;
  activity_key: string;
  origin_key: string;
  block_origins: Record<string, string>;
  resource_version_id: number | null;
  title: string;
  position: number;
  content: ContentPageV2 | null;
};

export type SourceItem = {
  sourceId: string;
  label: string;
  url: string;
  usage?: string | null;
};

export type SourcesBlock = {
  blockId: string;
  type: "sources";
  title: string;
  items: Array<SourceItem>;
};

export type SubmissionCoursePreview = {
  course_id: number;
  title: string;
  revision: number;
  state_token: string;
  base_release_id: number | null;
  pending_review_id: number | null;
  changes: Array<SyncChangeRead>;
  impact: CourseImpactRead;
  dependencies_sha256: string;
};

export type SubmissionItemRead = {
  candidate_id: number;
  status: "submitted" | "approved" | "rejected" | "withdrawn";
  review_version: number;
  course_id: number;
  review_item_id: number;
  revision_id: number;
};

export type SubmissionPreviewCommand = {
  source_revision: number;
  source_state_token: string;
  base_revision_id?: number | null;
  target_course_ids?: Array<number>;
  conflict_choices?: Record<string, "keep" | "replace">;
};

export type SubmissionPreviewRead = {
  source_course_id: number;
  source_revision: number;
  base_revision_id: number | null;
  courses: Array<SubmissionCoursePreview>;
  preview_token: string;
};

export type SubmissionReceiptRead = {
  batch_id: number;
  items: Array<SubmissionItemRead>;
  skipped: Array<SkippedCourseRead>;
};

export type SubmitCandidateCommand = {
  client_request_id: string;
  source_revision: number;
  source_state_token: string;
  base_revision_id?: number | null;
  target_course_ids?: Array<number>;
  conflict_choices?: Record<string, "keep" | "replace">;
  preview_token: string;
  result_policies?: Record<string, Record<string, "keep" | "redo">>;
  note?: string | null;
};

export type SyncChangeRead = {
  key: string;
  status: "ready" | "conflict" | "unchanged" | "skipped";
  unit_title: string;
  reason?: string | null;
  block_origin?: string | null;
  fields?: Array<string>;
  before?: Record<string, unknown> | null;
  after?: Record<string, unknown> | null;
  current?: Record<string, unknown> | null;
  unit_id?: number | null;
  block_id?: string | null;
};

export type SyncImpactRead = {
  source_course_id: number;
  source_revision_id: number;
  base_revision_id: number | null;
  applied_changes: Array<string>;
  preview_changes: Array<SyncChangeRead>;
};

export type UnitImpactRead = {
  unit_id: number;
  origin_key: string;
  title: string;
  change: "added" | "modified" | "unchanged";
  learning_changed: boolean;
  decision_required: boolean;
  default_policy: "keep" | "redo" | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
};

export type WithdrawCommand = {
  client_request_id: string;
  expected_version: number;
};

export type WorkflowReceiptRead = {
  client_request_id: string;
  operation_kind: string;
  response: Record<string, unknown>;
};
