// Generated by backend/scripts/export_portal_contracts.py. Do not edit DTOs by hand.

export type ChartSeries = {
  name: string;
  values: Array<number>;
};

export type DataChartConfig = {
  kind?: "bar" | "line";
  title: string;
  labels: Array<string>;
  series: Array<ChartSeries>;
  y_label?: string;
};

export type FunctionGraphConfig = {
  formula: string;
  parameters?: Array<FunctionParameter>;
  x_min?: number;
  x_max?: number;
  y_min?: number;
  y_max?: number;
  samples?: number;
};

export type FunctionParameter = {
  key: string;
  label: string;
  value: number;
  minimum: number;
  maximum: number;
  step: number;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type LearningLevelRead = {
  key: string;
  title: string;
};

export type LearningSpaceRead = {
  key: string;
  view: string;
  title: string;
  entry: string;
  kind: "legacy" | "bundle";
  accent: string;
};

export type LearningSpacesRead = {
  schema_version: "astra-learning-spaces-v1";
  spaces: Array<LearningSpaceRead>;
  levels: Array<LearningLevelRead>;
};

export type LegacyResourceConfig = Record<string, never>;

export type ResourceInstallationRead = {
  installed_versions: number;
  catalogue_size: number;
};

export type ResourcePage = {
  items: Array<ResourceVersionRead>;
  total: number;
  limit: number;
  offset: number;
  next_offset: number | null;
};

export type ResourcePreview = {
  configuration?: FunctionGraphConfig | DataChartConfig | LegacyResourceConfig;
};

export type ResourcePreviewRead = {
  resource_version_id: number;
  renderer: string;
  configuration: Record<string, unknown>;
  view: Record<string, unknown>;
};

export type ResourceVersionRead = {
  id: number;
  resource_key: string;
  space_key: string;
  subject_key: string;
  kind: "activity" | "template" | "media";
  version_number: number;
  title: string;
  renderer: string;
  definition: Record<string, unknown>;
  capabilities: Record<string, unknown>;
  provenance: Record<string, unknown>;
  content_sha256: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
};
